import localFont from 'next/font/local';
import 'bootstrap/dist/css/bootstrap.css';
import './globals.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import SideBar from '@/component/side-bar';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SideBar />
        {children}
      </body>
    </html>
  );
}
